services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: backend
    tty: true
    restart: always
    volumes:
      - type: bind
        source: ./src/backend
        target: /app
    ports:
      - 3000:3000
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: frontend
    tty: true
    restart: always
    environment:
      VITE_HOST_IP: ${IP:-host.docker.internal}
    volumes:
      - type: bind
        source: ./src/frontend
        target: /app
    ports:
      - 5173:5173
